services:
  personal_portfolio:
    volumes:
      - static:/static
    build:
      context: ./personal_portfolio
    ports:
      - "8000:8000"
    command: /entrypoint.sh

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - personal_portfolio
      - frontend

volumes:
  static:
  frontend:
